# version: 2
# updates:
# - package-ecosystem: npm
#   directory: "/"
#   schedule:
#     interval: daily
#     time: "06:30"
#   reviewers:
#   - gilbertly
#   labels:
#   - dependabot
#   allow:
#   - dependency-type: production
#   ignore:
#   - dependency-name: "@sentry/node"
#     versions:
#     - 6.0.2
#     - 6.0.3
#     - 6.0.4
#     - 6.2.0
#     - 6.2.1
#     - 6.2.2
#     - 6.2.3
#     - 6.2.4
#     - 6.2.5
#     - 6.3.0
#     - 6.3.1
#   - dependency-name: aws-sdk
#     versions:
#     - 2.833.0
#     - 2.834.0
#     - 2.835.0
#     - 2.836.0
#     - 2.838.0
#     - 2.840.0
#     - 2.841.0
#     - 2.842.0
#     - 2.843.0
#     - 2.844.0
#     - 2.845.0
#     - 2.846.0
#     - 2.847.0
#     - 2.848.0
#     - 2.849.0
#     - 2.850.0
#     - 2.851.0
#     - 2.852.0
#     - 2.853.0
#     - 2.854.0
#     - 2.855.0
#     - 2.856.0
#     - 2.857.0
#     - 2.858.0
#     - 2.859.0
#     - 2.860.0
#     - 2.861.0
#     - 2.862.0
#     - 2.863.0
#     - 2.864.0
#     - 2.865.0
#     - 2.866.0
#     - 2.867.0
#     - 2.868.0
#     - 2.869.0
#     - 2.870.0
#     - 2.871.0
#     - 2.873.0
#     - 2.874.0
#     - 2.875.0
#     - 2.876.0
#     - 2.878.0
#     - 2.879.0
#     - 2.880.0
#     - 2.881.0
#     - 2.882.0
#     - 2.883.0
#     - 2.884.0
#     - 2.885.0
#     - 2.886.0
#     - 2.889.0
#     - 2.890.0
#     - 2.891.0
#     - 2.892.0
#   - dependency-name: y18n
#     versions:
#     - 4.0.1
#     - 4.0.2
#   - dependency-name: lighthouse
#     versions:
#     - 7.0.1
