service: starter-ts
useDotenv: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack

custom:
  webpack:
    webpackConfig: config/webpack.config.js
    packagePath: .package.json
    includeModules: false
    excludeFiles: src/__tests__
    packager: npm
    forceExclude: [aws-sdk]
  param: ${file(./config/params.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 # seconds
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:provider.stage}-${self:service}
  logRetentionInDays: 7
  tags:
    project: ${self:provider.stage}-${self:service}
  apiGateway:
    apiKeySourceType: HEADER
    shouldStartNameWithService: true
    apiKeys:
      - ${self:provider.stage}-${self:service}
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    SENTRY_DSN: ${self:custom.param.${self:provider.stage}.sentryDSN}

layers:
  dependencies:
    name: ${self:provider.stage}-${self:service}
    description: Starter typescript project dependencies.
    # package:
    #   artifact: dependencies.zip
    compatibleRuntimes: [nodejs12.x]
    licenseInfo: MIT
    path: ./nodejs
    retain: false

functions:
  helloFunction:
    name: ${self:provider.stage}_hello_function_ts
    handler: src/functions/hello.handler
    description: Basic sample function.
    events:
      - http:
          path: /test
          method: get
          request:
            parameters:
              paths:
                message: false
          cors: true
          private: true
    iamRoleStatements:
      - Sid: AllowLambdaDynamoDBAccess
        Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:Query
        Resource: !GetAtt DynamodbTableHello.Arn
    layers: [!Ref DependenciesLambdaLayer]

resources:
  - ${file(./aws/cfnTemplateSections.yml)}
  - ${file(./aws/dynamodbTables.yml)}
