Resources:
  DynamodbTableHello:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.stage}-hello
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: hello_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: hello_id
          AttributeType: S
        - AttributeName: hello_status
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: hello-index
          KeySchema:
            - AttributeName: hello_status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
