name: featureBuildDeploy
on:
  push:
    branches: 
      - 'feat*'
      - 'ft*'
  pull_request:
    branches: 
      - 'feat*'
      - 'ft*'
    types: [closed]

jobs:
  buildDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # - name: Restore & cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i --no-package-lock
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    
      - name: Deploy feature branch
        env:
          BRANCH_HASH: $(echo -n '${{ github.ref }}' | md5sum | cut -d" " -f1 | cut -c1-7)
          BRANCH_URL: $(echo -n 'https://github.com/${{ github.repository }}/tree/${GITHUB_REF##*/}')
        run: npm run deploy:feat --stage=br-${{ env.BRANCH_HASH }} --branchRef=${{ env.BRANCH_URL }}
      
      - name: Remove feature branch
        if: github.event.pull_request.merged == true
        env:
          BRANCH_HASH: $(echo -n '${{ github.ref }}' | md5sum | cut -d" " -f1 | cut -c1-7)
        run: npm run remove:feat --stage=br-${{ env.BRANCH_HASH }}
