name: pullRequest
on:
  pull_request:
    branches: 
      - 'feat*'
      - 'ft*'
    types: [opened, synchronize, closed, reopened, edited]

jobs:
  buildDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Restore & cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i --no-package-lock
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    
      - name: Deploy feature branch
        # if: pull_request.types == 'opened' || pull_request.types == 'synchronize'
        run: npm run deploy:feat pr${GITHUB_REF##*/}
      
      # - name: Remove feature branch
      #   if: pull_request.types == 'closed'
      #   run: npm run remove:feat pr${GITHUB_REF##*/}
